name: "Load & Publish Docker Image"
description: "Load Docker image from artifact and publish to ECR"
inputs:
  image:
    description: "service to build"
    required: true
    default: ""
  tag-prefix:
    description: "tag prefix"
    required: true
    default: ""   
  ecr_aws_access_key_id:
    description: "ecr aws access key id"
    required: true
    default: ""      
  ecr_aws_secret_key:
    description: "ecr aws secret key"
    required: true
    default: "" 
outputs:
  image-tag:
    description: "Pushed image tag"
    value: ${{ env.BUILD_TAG }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ inputs.ecr_aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.ecr_aws_secret_key }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: docker-image-${{inputs.image}}${{inputs.tag-prefix}}
        path: ${{ runner.temp }}

    - name: Load image
      shell: bash    
      run: |
        docker load --input ${{ runner.temp }}/image${{inputs.tag-prefix}}.tar
        docker image ls -a

    - name: Set tag
      shell: bash
      env:
        RUN_NUMBER: ${{ github.run_number }}
        START_FROM: ${{ inputs.start-build-from || 0 }}
      run: |
        BUILD_NUMBER=$(($RUN_NUMBER + $START_FROM))
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV

    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        state: open
    - name: Debug variables
      shell: bash
      run: |
        echo "github.ref: ${{ github.ref }}"
        echo "inputs.tag-prefix: ${{ inputs.tag-prefix }}"
        echo "env.BUILD_NUMBER: ${{ env.BUILD_NUMBER }}"
        echo "steps.findPr.outputs.pr: ${{ steps.findPr.outputs.pr }}"        

    - name: Determine tag, build and push Docker image
      shell: bash
      run: |
        # Determine BUILD_TAG based on git reference
        if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == "refs/heads/main" ]]; then
          BUILD_TAG="${{ inputs.tag-prefix }}oneclick-${{ env.BUILD_NUMBER }}"
        elif [[ "${{ github.ref }}" == *"release"* ]]; then
          BUILD_TAG="${{ inputs.tag-prefix }}oneclickrelease-${{ env.BUILD_NUMBER }}"
        elif [[ -n "${{ steps.findPr.outputs.pr }}" ]]; then
          BUILD_TAG="${{ inputs.tag-prefix }}oneclickpr-${{ steps.findPr.outputs.pr }}-${{ env.BUILD_NUMBER }}"
        else
          BUILD_TAG="${{ inputs.tag-prefix }}oneclick-${{ env.BUILD_NUMBER }}"
        fi

        echo "BUILD TAG: ${BUILD_TAG}"

        # Define the IMAGE variable explicitly
        IMAGE="${{ steps.login-ecr.outputs.registry }}/${{inputs.image}}:$BUILD_TAG"

        # Push the Docker image
        docker push "$IMAGE"