name: "Build & Export Docker Image"
description: "Build and export Docker image as artifact"
inputs:
  start-build-from:
    description: "the build number to start from"
    required: false
    default: "0"
  image:
    description: "service to build"
    required: true
    default: ""
  tag-prefix:
    description: "tag prefix"
    required: true
    default: ""    
  dockerfile:
    description: "docker file"
    required: true
    default: ""
  build-args:
    description: "set build-time variables"
    required: false
    default: ""
  ssh_key:    
    description: "ssh key"
    required: true
    default: ""
  ssh_known_hosts:
    description: "ssh known hosts"
    required: true
    default: ""
  git_fetch_submodules:
    description: "checkout and fetch submodules"
    default: "true"
  ecr_aws_access_key_id:
    description: "ecr aws access key id"
    required: true
    default: ""      
  ecr_aws_secret_key:
    description: "ecr aws secret key"
    required: true
    default: "" 
  dockerhub_username:
    description: "dockerhub username"
    required: true
    default: "tazerr"
  dockerhub_pull_token:
    description: "dockerhub pull token"
    required: true
  platform:
    description: "Target platform (e.g., linux/amd64, linux/arm64)"
    required: false
    default: "linux/amd64"
runs:
  using: composite
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.ecr_aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.ecr_aws_secret_key }}
        aws-region: eu-west-1

    - name: Docker Hub login
      shell: bash
      run: echo "${{ inputs.dockerhub_pull_token }}" | docker login -u "${{ inputs.dockerhub_username }}" --password-stdin

    - name: DHI registry login
      shell: bash
      run: echo "${{ inputs.dockerhub_pull_token }}" | docker login dhi.io -u "${{ inputs.dockerhub_username }}" --password-stdin         
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr  
    - uses: actions/checkout@v5
      if: inputs.git_fetch_submodules == 'true'
      with:
        submodules: recursive
        ssh-key: ${{ inputs.ssh_key }}    
    - uses: actions/checkout@v5
      if: inputs.git_fetch_submodules != 'true'      
    - name: Install SSH Key
      # You may pin to the exact commit or the version.
      # uses: shimataro/ssh-key-action@3c9b0fc6f2d223b8450b02a0445f526350fc73e0
      uses: shimataro/ssh-key-action@v2.3.1
      with:
        key: ${{ inputs.ssh_key }}
        known_hosts: ${{ inputs.ssh_known_hosts }}         
    - name: Copy SSH Key
      shell: bash
      run: cp ~/.ssh/id_rsa .
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [registry."dhi.io"]
            mirrors = ["dhi.io"]
    - name: Set platform suffix
      id: platform
      shell: bash
      run: |
        PLATFORM="${{ inputs.platform }}"
        PLATFORM_SUFFIX="${PLATFORM//\//-}"
        ARCH="${PLATFORM#*/}"
        echo "suffix=$PLATFORM_SUFFIX" >> $GITHUB_OUTPUT
        echo "arch=$ARCH" >> $GITHUB_OUTPUT        
    - name: Set tag
      shell: bash
      env:
        RUN_NUMBER: ${{github.run_number}}
        START_FROM: ${{inputs.start-build-from}}
      run: |
        echo $RUN_NUMBER
        echo $(($RUN_NUMBER+$START_FROM))
        echo BUILD_NUMBER=$(($RUN_NUMBER+$START_FROM)) >> $GITHUB_ENV
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        # Can be "open", "closed", or "all".  Defaults to "open".
        state: open
    - name: Build and push
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v6
      with:
          context: .
          platforms: ${{ inputs.platform }}
          push: true
          provenance: false
          sbom: false
          outputs: type=image,push=true,oci-mediatypes=true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{inputs.image}}:${{inputs.tag-prefix}}oneclick-${{ env.BUILD_NUMBER }}-${{ steps.platform.outputs.arch }}
          file: ${{inputs.dockerfile}}
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }}
          cache-to: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }},mode=max
    - name: Build and push PR
      if: (github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main') && steps.findPr.outputs.number > 0
      uses: docker/build-push-action@v6
      with:
          context: .
          platforms: ${{ inputs.platform }}
          push: true
          provenance: false
          sbom: false
          outputs: type=image,push=true,oci-mediatypes=true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{inputs.image}}:${{inputs.tag-prefix}}oneclickpr-${{ steps.findPr.outputs.pr }}-${{ env.BUILD_NUMBER }}-${{ steps.platform.outputs.arch }}
          file: ${{inputs.dockerfile}}
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }}
          cache-to: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }},mode=max
    - name: Comment oneclick PR tag
      if: (github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main') && steps.findPr.outputs.number > 0
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        header: OneClick PR tag
        recreate: true
        message: |
          Your build has the image tag: `${{inputs.tag-prefix}}oneclickpr-${{ steps.findPr.outputs.pr }}-${{ env.BUILD_NUMBER }}` :sparkles:
    - name: Build and push Release
      if: contains(github.ref, 'release')
      uses: docker/build-push-action@v6
      with:
          context: .
          platforms: ${{ inputs.platform }}
          push: true
          provenance: false
          sbom: false
          outputs: type=image,push=true,oci-mediatypes=true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{inputs.image}}:${{inputs.tag-prefix}}oneclickrelease-${{ env.BUILD_NUMBER }}-${{ steps.platform.outputs.arch }}
          file: ${{inputs.dockerfile}}
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }}
          cache-to: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }},mode=max