name: "Build & Publish"
description: "Build and publish the Docker image"
inputs:
  start-build-from:
    description: "the build number to start from"
    required: false
    default: "0"
  image:
    description: "service to build"
    required: true
    default: ""
  tag-prefix:
    description: "tag prefix"
    required: true
    default: ""
  dockerfile:
    description: "docker file"
    required: true
    default: ""
  build-args:
    description: "set build-time variables"
    required: false
    default: ""
  ssh_key:
    description: "ssh key"
    required: true
    default: ""
  ssh_known_hosts:
    description: "ssh known hosts"
    required: true
    default: ""
  ecr_aws_access_key_id:
    description: "ecr aws access key id"
    required: true
    default: ""
  ecr_aws_secret_key:
    description: "ecr aws secret key"
    required: true
    default: ""
  git_fetch_submodules:
    description: "checkout and fetch submodules"
    default: "true"
  github_token:
    description: "github token"
    required: true
    default: ""
  latest_tag:
    description: "latest tag"
    required: false
    default: "false"
  dockerhub_username:
    description: "dockerhub username"
    required: true
    default: "tazerr"
  dockerhub_pull_token:
    description: "dockerhub pull token"
    required: true
  platform:
    description: "Target platform (e.g., linux/amd64, linux/arm64)"
    required: false
    default: "linux/amd64"
outputs:
  image-tag:
    description: "The pushed image tag (without registry)"
    value: ${{ steps.set-output.outputs.image-tag }}
  full-image:
    description: "The full pushed image with registry"
    value: ${{ steps.set-output.outputs.full-image }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
      if: inputs.git_fetch_submodules == 'true'
      with:
        submodules: recursive
        ssh-key: ${{ inputs.ssh_key }}
    - uses: actions/checkout@v5
      if: inputs.git_fetch_submodules != 'true'
    - name: Install SSH Key
      # You may pin to the exact commit or the version.
      # uses: shimataro/ssh-key-action@3c9b0fc6f2d223b8450b02a0445f526350fc73e0
      uses: shimataro/ssh-key-action@v2.3.1
      with:
        key: ${{ inputs.ssh_key }}
        known_hosts: ${{ inputs.ssh_known_hosts }}
    - name: Copy SSH Key
      shell: bash
      run: cp ~/.ssh/id_rsa .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ inputs.ecr_aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.ecr_aws_secret_key }}
        aws-region: eu-west-1
    - name: Docker Hub login
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_pull_token }}

    - name: DHI registry login
      uses: docker/login-action@v3
      with:
        registry: dhi.io
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_pull_token }}                 
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [registry."dhi.io"]
            mirrors = ["dhi.io"]
    - name: Set platform suffix
      id: platform
      shell: bash
      run: |
        PLATFORM="${{ inputs.platform }}"
        # Convert linux/amd64 to linux-amd64
        PLATFORM_SUFFIX="${PLATFORM//\//-}"
        # Extract just the arch (amd64, arm64)
        ARCH="${PLATFORM#*/}"
        echo "suffix=$PLATFORM_SUFFIX" >> $GITHUB_OUTPUT
        echo "arch=$ARCH" >> $GITHUB_OUTPUT
    - name: Set tag
      shell: bash
      env:
        RUN_NUMBER: ${{github.run_number}}
        START_FROM: ${{inputs.start-build-from}}
      run: |
        echo $RUN_NUMBER
        echo $(($RUN_NUMBER+$START_FROM))
        echo BUILD_NUMBER=$(($RUN_NUMBER+$START_FROM)) >> $GITHUB_ENV
    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        # Can be "open", "closed", or "all".  Defaults to "open".
        state: open
    - name: Build and push
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ inputs.platform }}
        push: true
        provenance: false
        sbom: false
        outputs: type=image,push=true,oci-mediatypes=true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{inputs.image}}:${{inputs.tag-prefix}}oneclick-${{ env.BUILD_NUMBER }}-${{ steps.platform.outputs.arch }}
        file: ${{inputs.dockerfile}}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }}
        cache-to: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }},mode=max
    - name: Build and push latest
      if: (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') && inputs.latest_tag == 'true'
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ inputs.platform }}
        push: true
        provenance: false
        sbom: false
        outputs: type=image,push=true,oci-mediatypes=true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{inputs.image}}:${{inputs.tag-prefix}}latest-${{ steps.platform.outputs.arch }}
        file: ${{inputs.dockerfile}}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }}
        cache-to: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }},mode=max
    - name: Build and push PR
      if: (github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main') && steps.findPr.outputs.number > 0
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ inputs.platform }}
        push: true
        provenance: false
        sbom: false
        outputs: type=image,push=true,oci-mediatypes=true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{inputs.image}}:${{inputs.tag-prefix}}oneclickpr-${{ steps.findPr.outputs.pr }}-${{ env.BUILD_NUMBER }}-${{ steps.platform.outputs.arch }}
        file: ${{inputs.dockerfile}}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }}
        cache-to: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }},mode=max
    - name: Comment oneclick PR tag
      if: (github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main') && steps.findPr.outputs.number > 0
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        header: OneClick PR tag
        recreate: true
        message: |
          Your build has the image tag: `${{inputs.tag-prefix}}oneclickpr-${{ steps.findPr.outputs.pr }}-${{ env.BUILD_NUMBER }}` :sparkles:
    - name: Build and push Release
      if: contains(github.ref, 'release')
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ inputs.platform }}
        push: true
        provenance: false
        sbom: false
        outputs: type=image,push=true,oci-mediatypes=true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{inputs.image}}:${{inputs.tag-prefix}}oneclickrelease-${{ env.BUILD_NUMBER }}-${{ steps.platform.outputs.arch }}
        file: ${{inputs.dockerfile}}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }}
        cache-to: type=gha,scope=${{ inputs.image }}-${{ steps.platform.outputs.suffix }},mode=max
    - name: Set outputs
      id: set-output
      shell: bash
      run: |
        # Determine the base tag (without arch suffix)
        if [[ "${{ github.ref }}" == "refs/heads/master" || "${{ github.ref }}" == "refs/heads/main" ]]; then
          BASE_TAG="${{ inputs.tag-prefix }}oneclick-${{ env.BUILD_NUMBER }}"
        elif [[ "${{ github.ref }}" == *"release"* ]]; then
          BASE_TAG="${{ inputs.tag-prefix }}oneclickrelease-${{ env.BUILD_NUMBER }}"
        elif [[ -n "${{ steps.findPr.outputs.pr }}" ]]; then
          BASE_TAG="${{ inputs.tag-prefix }}oneclickpr-${{ steps.findPr.outputs.pr }}-${{ env.BUILD_NUMBER }}"
        else
          BASE_TAG="${{ inputs.tag-prefix }}oneclick-${{ env.BUILD_NUMBER }}"
        fi

        ARCH_TAG="${BASE_TAG}-${{ steps.platform.outputs.arch }}"
        FULL_IMAGE="${{ steps.login-ecr.outputs.registry }}/${{ inputs.image }}:${ARCH_TAG}"

        echo "image-tag=${ARCH_TAG}" >> $GITHUB_OUTPUT
        echo "full-image=${FULL_IMAGE}" >> $GITHUB_OUTPUT
        echo "base-tag=${BASE_TAG}" >> $GITHUB_OUTPUT
