name: Bump Version
on:
  workflow_call:
    inputs:
      start-build-from:
        required: false
        type: string
        default: "0"
      is-library:
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set tag
        shell: bash
        env:
          RUN_NUMBER: ${{github.run_number}}
          START_FROM: ${{inputs.start-build-from}}
        run: |
          echo $RUN_NUMBER
          echo $(($RUN_NUMBER+$START_FROM))
          echo BUILD_NUMBER=$(($RUN_NUMBER+$START_FROM)) >> $GITHUB_ENV
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - name: Bump version and push tag (service)
        if: ${{!inputs.is-library}} && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.token }}
          custom_tag: oneclick-${{ env.BUILD_NUMBER }}
          tag_prefix: ""
      - name: Bump version and push tag (library)
        if: ${{inputs.is-library}} && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Bump version and push tag PR
        if: (github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main') && steps.findPr.outputs.number > 0
        id: tag_version_pr
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.token }}
          custom_tag: oneclickpr-${{ env.BUILD_NUMBER }}
          tag_prefix: ""
      - name: Create a GitHub release PR
        if: (github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main') && steps.findPr.outputs.number > 0
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ steps.tag_version_pr.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version_pr.outputs.new_tag }}
          body: ${{ steps.tag_version_pr.outputs.changelog }}
      - name: Bump version and push tag Release Branch
        if: contains(github.ref, 'release')
        id: tag_version_release
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.token }}
          custom_tag: oneclickrelease-${{ env.BUILD_NUMBER }}
          tag_prefix: ""
      - name: Create a GitHub release branch
        if: contains(github.ref, 'release')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ steps.tag_version_release.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version_release.outputs.new_tag }}
          body: ${{ steps.tag_version_release.outputs.changelog }}
