name: Bump Version
on:
  workflow_call:
    inputs:
      start-build-from:
        required: false
        type: string
        default: "0"
      default_branch:
        required: false
        type: string
        default: "main"
    secrets:
      token:
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        if: ${{ github.ref == 'refs/heads/master' }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
