name: Bump Version
on:
  workflow_call:
    inputs:
      start-build-from:
        required: false
        type: string
        default: "0"
      is-library:
        required: false
        default: false
        type: boolean
      create-release:
        required: false
        default: true
        type: boolean
    secrets:
      token:
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.set_output.outputs.upload_url }}    
    steps:
      - name: Set tag
        shell: bash
        env:
          RUN_NUMBER: ${{github.run_number}}
          START_FROM: ${{inputs.start-build-from}}
        run: |
          echo $RUN_NUMBER
          echo $(($RUN_NUMBER+$START_FROM))
          echo BUILD_NUMBER=$(($RUN_NUMBER+$START_FROM)) >> $GITHUB_ENV
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open
      - if: ${{ inputs.is-library == false && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') }}
        name: Bump version and push tag (service)
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.token }}
          custom_tag: oneclick-${{ env.BUILD_NUMBER }}
          tag_prefix: ""
      - if: ${{ inputs.is-library == true && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') }}
        name: Bump version and push tag (library)
        id: tag_version_lib
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.token }}
      - if: ${{ inputs.create-release == true && inputs.is-library == false && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') }}
        name: Create a GitHub release (service)
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - if: ${{ inputs.create-release == true && inputs.is-library == true && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') }}
        name: Create a GitHub release (library)
        id: create_release_lib
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ steps.tag_version_lib.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version_lib.outputs.new_tag }}
          body: ${{ steps.tag_version_lib.outputs.changelog }}
      - name: Set output for release URL
        id: set_output
        if: ${{ inputs.create-release == true && inputs.is-library == true && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main') }}
        run: |
          echo "upload_url=${{ steps.create_release_lib.outputs.upload_url }}" >> $GITHUB_OUTPUT
      - name: Bump version and push tag PR (service)
        if: ${{ inputs.is-library == false && (github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main') && steps.findPr.outputs.number > 0 }}
        id: tag_version_pr
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.token }}
          custom_tag: oneclickpr-${{ env.BUILD_NUMBER }}
          tag_prefix: ""
      - name: Bump version and push tag PR (library)
        if: ${{ inputs.is-library == true && (github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main') && steps.findPr.outputs.number > 0 }}
        id: tag_version_pr_lib
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.token }}
          custom_tag: pr-${{ env.BUILD_NUMBER }}
          tag_prefix: ""
      - name: Create a GitHub release PR (service)
        if: ${{ inputs.create-release == true && inputs.is-library == false && (github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main') && steps.findPr.outputs.number > 0 }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ steps.tag_version_pr.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version_pr.outputs.new_tag }}
          body: ${{ steps.tag_version_pr.outputs.changelog }}
      - name: Create a GitHub release PR (library)
        if: ${{ inputs.create-release == true && inputs.is-library == true && (github.ref != 'refs/heads/master' || github.ref != 'refs/heads/main') && steps.findPr.outputs.number > 0 }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ steps.tag_version_pr_lib.outputs.new_tag }}
      - name: Bump version and push tag Release Branch (service)
        if: ${{ inputs.is-library == false && contains(github.ref, 'release') }}
        id: tag_version_release
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.token }}
          custom_tag: oneclickrelease-${{ env.BUILD_NUMBER }}
          tag_prefix: ""
      - name: Bump version and push tag Release Branch (library)
        if: ${{ inputs.is-library == true && contains(github.ref, 'release') }}
        id: tag_version_release_lib
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.token }}
      - name: Create a GitHub release branch
        if: ${{inputs.create-release == true && contains(github.ref, 'release') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ steps.tag_version_release.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version_release.outputs.new_tag }}
          body: ${{ steps.tag_version_release.outputs.changelog }}
